[package]

name = "synthizer"
version = "0.0.1"
authors = ["Noah Weninger"]

[dependencies]
rustc-serialize = "*"
docopt_macros = "*"

[dependencies.regex]
git = "https://github.com/rust-lang/regex"

[dependencies.regex_macros]
git = "https://github.com/rust-lang/regex"
