[package]

name = "synthizer"
version = "0.0.1"
authors = ["Noah Weninger"]

[dependencies]
rustc-serialize = "*"
docopt = "*"
docopt_macros = "*"
regex = "*"
regex_macros = "*"

[lib]
name = "interpreter"
path = "src/interpreter/lib.rs"

[[bin]]
name = "synthizer"
path = "src/cli/main.rs"
